#!/bin/sh

# Where is the OSV? (Where is your build.xml?)
export OSV_HOME=../../../osv
# If Mac OS X, which version of Java should we use?
export JAVA_VERSION=1.8.0

# Where will Java look for classes? 
# Add other jars to this list as necessary.
export CLASSPATH=\
$OSV_HOME/libs/ipf.jar:\
$OSV_HOME/libs/edu-mines-jtk-1.0.0.jar:\
$OSV_HOME/libs/gluegen-rt.jar:\
$OSV_HOME/libs/jogl-all.jar:\
$OSV_HOME/libs/jythonlib.jar:\
$OSV_HOME/build/classes:\
.

# Run a server 64-bit VM with assertions enabled and a 1GB max Java heap.
# Modify these flags and properties as necessary for your system.

java -server -d64 -ea -Xmx18g \
-Djava.library.path=$JAVA_LIBRARY_PATH \
-Djava.util.logging.config.file=$HOME/.java_logging_config \
-Dpython.cachedir.skip=false \
-Dpython.cachedir=/tmp/cachedir \
org.python.util.jython $*

